---
# Fleet Inventory — Starfall Defence Corps
# Mixed OS fleet: Ubuntu and Rocky Linux.

all:
  children:
    debian:
      children:
        web_servers:
          hosts:
            sdc-web:
              ansible_host: localhost
              ansible_port: 2221
              ansible_user: cadet
              ansible_ssh_private_key_file: .ssh/cadet_key
        comms_relays:
          hosts:
            sdc-comms:
              ansible_host: localhost
              ansible_port: 2223
              ansible_user: cadet
              ansible_ssh_private_key_file: .ssh/cadet_key
    redhat:
      children:
        db_servers:
          hosts:
            sdc-db:
              ansible_host: localhost
              ansible_port: 2222
              ansible_user: cadet
              ansible_ssh_private_key_file: .ssh/cadet_key
