dependency:
  name: galaxy

driver:
  name: default

platforms:
  - name: sdc-web
    managed: false
    groups:
      - fleet
      - debian
      - web_servers
  - name: sdc-db
    managed: false
    groups:
      - fleet
      - redhat
      - db_servers
  - name: sdc-comms
    managed: false
    groups:
      - fleet
      - debian
      - comms_relays

provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory/hosts.yml

verifier:
  name: testinfra
  directory: tests/
